### ISSUE TITLE
Ability to add custom properties to the NAR archive's MANIFEST file

### ISSUE THREAD

**Issue by lmserrano** [tonykoval/sbt-nifi-nar#2]
Is there any way to add custom properties to the NAR archive's MANIFEST file? I am not finding a way to do this but it would be a useful feature.

Plugins like `sbt` allows configuring this in a way as follows, in the `build.sbt` file settings:

```
  packageOptions := Seq(
    ManifestAttributes(
      ("Custom-Key", "Custom-Value")
   )
  )
```

However, the plugin seems to be ignoring these in the generated NAR archive, because it uses a fixed set of key value pairs: https://github.com/tonykoval/sbt-nifi-nar/blob/7c7bd4e077d446d23fe0673d659587aa881a62b5/src/main/scala/sk/vub/sbt/nifi/NarPlugin.scala#L206-L220

**Comment by tonykoval** [comment]
Hi, thank you for the request. I added this functionality to the plugin and I'll create a new release.

**Comment by lmserrano** [comment]
Thank you for adding this feature, and also for creating and maintaining this very useful plugin!
